export const question = 
    {
        prompt: "Rank these US states from most to fewest population",
        items: [
            { item: "California", number: 39896400, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_California.svg/500px-Flag_of_California.svg.png" },
                { item: "Texas", number: 32416700, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Flag_of_Texas.svg/500px-Flag_of_Texas.svg.png" },
                { item: "Florida", number: 24306900, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Flag_of_Florida.svg/500px-Flag_of_Florida.svg.png" },
                { item: "New York", number: 20127000, image: "" },
                { item: "Pennsylvania", number: 13200800, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Flag_of_Pennsylvania.svg/500px-Flag_of_Pennsylvania.svg.png" },
                { item: "Illinois", number: 12846000, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Illinois.svg/500px-Flag_of_Illinois.svg.png" },
                { item: "Ohio", number: 12001800, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Ohio.svg/500px-Flag_of_Ohio.svg.png" },
                { item: "Georgia", number: 11413800, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Flag_of_the_State_of_Georgia.svg/500px-Flag_of_the_State_of_Georgia.svg.png" },
                { item: "North Carolina", number: 11375700, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Flag_of_North_Carolina.svg/500px-Flag_of_North_Carolina.svg.png" },
                { item: "Michigan", number: 10254700, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Flag_of_Michigan.svg/500px-Flag_of_Michigan.svg.png" },
                { item: "New Jersey", number: 9743270, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_New_Jersey.svg/500px-Flag_of_New_Jersey.svg.png" },
                { item: "Virginia", number: 8964220, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Flag_of_Virginia.svg/500px-Flag_of_Virginia.svg.png" },
                { item: "Washington", number: 8159900, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Flag_of_Washington.svg/500px-Flag_of_Washington.svg.png" },
                { item: "Arizona", number: 7801100, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Flag_of_Arizona.svg/500px-Flag_of_Arizona.svg.png" },
                { item: "Tennessee", number: 7386640, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Tennessee.svg/500px-Flag_of_Tennessee.svg.png" },
                { item: "Massachusetts", number: 7275380, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Flag_of_Massachusetts.svg/500px-Flag_of_Massachusetts.svg.png" },
                { item: "Indiana", number: 7012560, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Flag_of_Indiana.svg/500px-Flag_of_Indiana.svg.png" },
                { item: "Maryland", number: 6355540, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Flag_of_Maryland.svg/500px-Flag_of_Maryland.svg.png" },
                { item: "Missouri", number: 6320320, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Flag_of_Missouri.svg/500px-Flag_of_Missouri.svg.png" },
                { item: "Colorado", number: 6069800, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Flag_of_Colorado.svg/500px-Flag_of_Colorado.svg.png" },
                { item: "Wisconsin", number: 6022120, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Flag_of_Wisconsin.svg/500px-Flag_of_Wisconsin.svg.png" },
                { item: "Minnesota", number: 5873360, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Flag_of_Minnesota.svg/500px-Flag_of_Minnesota.svg.png" },
                { item: "South Carolina", number: 5660830, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Flag_of_South_Carolina.svg/500px-Flag_of_South_Carolina.svg.png" },
                { item: "Alabama", number: 5237750, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Alabama.svg/500px-Flag_of_Alabama.svg.png" },
                { item: "Kentucky", number: 4663930, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Flag_of_Kentucky.svg/500px-Flag_of_Kentucky.svg.png" },
                { item: "Louisiana", number: 4617080, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Flag_of_Louisiana.svg/500px-Flag_of_Louisiana.svg.png" },
                { item: "Oregon", number: 4309810, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Flag_of_Oregon.svg/500px-Flag_of_Oregon.svg.png" },
                { item: "Oklahoma", number: 4158420, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Flag_of_Oklahoma.svg/500px-Flag_of_Oklahoma.svg.png" },
                { item: "Connecticut", number: 3739160, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Flag_of_Connecticut.svg/500px-Flag_of_Connecticut.svg.png" },
                { item: "Utah", number: 3624400, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Utah.svg/500px-Flag_of_Utah.svg.png" },
                { item: "Nevada", number: 3373680, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Flag_of_Nevada.svg/500px-Flag_of_Nevada.svg.png" },
                { item: "Iowa", number: 3287640, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Flag_of_Iowa.svg/500px-Flag_of_Iowa.svg.png" },
                { item: "Arkansas", number: 3126140, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Flag_of_Arkansas.svg/500px-Flag_of_Arkansas.svg.png" },
                { item: "Kansas", number: 3008820, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Flag_of_Kansas.svg/500px-Flag_of_Kansas.svg.png" },
                { item: "Mississippi", number: 2942790, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Flag_of_Mississippi.svg/500px-Flag_of_Mississippi.svg.png" },
                { item: "New Mexico", number: 2148440, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_New_Mexico.svg/500px-Flag_of_New_Mexico.svg.png" },
                { item: "Idaho", number: 2062610, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_Idaho.svg/500px-Flag_of_Idaho.svg.png" },
                { item: "Nebraska", number: 2040670, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Flag_of_Nebraska.svg/500px-Flag_of_Nebraska.svg.png" },
                { item: "West Virginia", number: 1768950, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Flag_of_West_Virginia.svg/500px-Flag_of_West_Virginia.svg.png" },
                { item: "Hawaii", number: 1455660, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Flag_of_Hawaii.svg/500px-Flag_of_Hawaii.svg.png" },
                { item: "New Hampshire", number: 1422700, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Flag_of_New_Hampshire.svg/500px-Flag_of_New_Hampshire.svg.png" },
                { item: "Maine", number: 1415740, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Flag_of_the_State_of_Maine.svg/500px-Flag_of_the_State_of_Maine.svg.png" },
                { item: "Montana", number: 1149100, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_Montana.svg/500px-Flag_of_Montana.svg.png" },
                { item: "Rhode Island", number: 1130070, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Rhode_Island.svg/500px-Flag_of_Rhode_Island.svg.png" },
                { item: "Delaware", number: 1082900, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Flag_of_Delaware.svg/500px-Flag_of_Delaware.svg.png" },
                { item: "South Dakota", number: 937397, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_South_Dakota.svg/500px-Flag_of_South_Dakota.svg.png" },
                { item: "North Dakota", number: 811610, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Flag_of_North_Dakota.svg/500px-Flag_of_North_Dakota.svg.png" },
                { item: "Alaska", number: 747379, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Flag_of_Alaska.svg/500px-Flag_of_Alaska.svg.png" },
                { item: "Vermont", number: 648063, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Vermont.svg/500px-Flag_of_Vermont.svg.png" },
                { item: "Wyoming", number: 592720, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Wyoming.svg/500px-Flag_of_Wyoming.svg.png" }
        ]
    };
