export const question = 
    {
        prompt: "Rank these FIFA member nations by total World Cup appearances (through 2022) from most to fewest",
        items: [
            { item: "Brazil", number: 23, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Brazilian_Football_Confederation_logo.svg/500px-Brazilian_Football_Confederation_logo.svg.png" },
                { item: "Germany", number: 21, image: "" },
                { item: "Argentina", number: 19, image: "" },
                { item: "Italy", number: 18, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Logo_Italy_National_Football_Team_-_2023.svg/500px-Logo_Italy_National_Football_Team_-_2023.svg.png" },
                { item: "Mexico", number: 18, image: "" },
                { item: "Spain", number: 17, image: "" },
                { item: "England", number: 17, image: "" },
                { item: "France", number: 17, image: "" },
                { item: "Belgium", number: 15, image: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f9/Royal_Belgian_FA_logo_2019.svg/500px-Royal_Belgian_FA_logo_2019.svg.png" },
                { item: "Uruguay", number: 15, image: "" },
                { item: "Switzerland", number: 13, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Flag_of_Switzerland_%28Pantone%29.svg/500px-Flag_of_Switzerland_%28Pantone%29.svg.png" },
                { item: "Serbia", number: 13, image: "" },
                { item: "South Korea", number: 12, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/500px-Flag_of_South_Korea.svg.png" },
                { item: "United States", number: 12, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/United_States_Soccer_Federation_logo.svg/500px-United_States_Soccer_Federation_logo.svg.png" },
                { item: "Netherlands", number: 12, image: "" },
                { item: "Sweden", number: 12, image: "" },
                { item: "Russia", number: 11, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Coat_of_Arms_of_the_Russian_Federation_2.svg/500px-Coat_of_Arms_of_the_Russian_Federation_2.svg.png" },
                { item: "Portugal", number: 9, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Portugal_National_Team_logo.png/500px-Portugal_National_Team_logo.png" },
                { item: "Scotland", number: 9, image: "" },
                { item: "Poland", number: 9, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Herb_Polski.svg/500px-Herb_Polski.svg.png" },
                { item: "Paraguay", number: 9, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Asociaci%C3%B3n_Paraguaya_de_F%C3%BAtbol_logo.svg/500px-Asociaci%C3%B3n_Paraguaya_de_F%C3%BAtbol_logo.svg.png" },
                { item: "Hungary", number: 9, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Coat_of_arms_of_Hungary.svg/500px-Coat_of_arms_of_Hungary.svg.png" },
                { item: "Czech Republic", number: 9, image: "" },
                { item: "Slovakia", number: 9, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Coat_of_arms_of_Slovakia.svg/500px-Coat_of_arms_of_Slovakia.svg.png" },
                { item: "Chile", number: 9, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Federaci%C3%B3n_de_F%C3%BAtbol_de_Chile_logo.svg/500px-Federaci%C3%B3n_de_F%C3%BAtbol_de_Chile_logo.svg.png" },
                { item: "Japan", number: 8, image: "" },
                { item: "Cameroon", number: 8, image: "" },
                { item: "Austria", number: 8, image: "" },
                { item: "Australia", number: 7, image: "" },
                { item: "Croatia", number: 7, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/500px-Flag_of_Croatia.svg.png" },
                { item: "Iran", number: 7, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/500px-Flag_of_Iran.svg.png" },
                { item: "Saudi Arabia", number: 7, image: "" },
                { item: "Bulgaria", number: 7, image: "" },
                { item: "Morocco", number: 7, image: "" },
                { item: "Tunisia", number: 7, image: "" },
                { item: "Colombia", number: 7, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/FCF-Logo-2023.svg/500px-FCF-Logo-2023.svg.png" },
                { item: "Romania", number: 7, image: "" },
                { item: "Costa Rica", number: 6, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Costa_Rica_national_football_team_logo.svg/500px-Costa_Rica_national_football_team_logo.svg.png" },
                { item: "Nigeria", number: 6, image: "" },
                { item: "Denmark", number: 6, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Dansk_boldspil_union_logo.svg/500px-Dansk_boldspil_union_logo.svg.png" },
                { item: "Ghana", number: 5, image: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Ghana_Football_Association_logo.png" },
                { item: "Ecuador", number: 5, image: "" },
                { item: "Algeria", number: 5, image: "" },
                { item: "Peru", number: 5, image: "https://upload.wikimedia.org/wikipedia/en/thumb/3/36/Fpf-logo.svg/500px-Fpf-logo.svg.png" },
                { item: "Senegal", number: 4, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Flag_of_Senegal.svg/500px-Flag_of_Senegal.svg.png" },
                { item: "Ivory Coast", number: 4, image: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Cote_Divoire_Enblem.png" },
                { item: "Norway", number: 4, image: "" },
                { item: "South Africa", number: 4, image: "" },
                { item: "Egypt", number: 4, image: "" },
                { item: "Canada", number: 3, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Canadian_Soccer_Association_logo.svg/500px-Canadian_Soccer_Association_logo.svg.png" }
        ]
    };
